language: node_js
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- '8.7'

install:
- yarn install


jobs:
  include:
    - stage: test
      env:
        global:
          - CC_TEST_REPORTER_ID=c3f27ead4c37b583e87fb47452b505b9c823f676564c86a53745c6cf28026253

      script: npm run test:ci



      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build


      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov -d -r c3f27ead4c37b583e87fb47452b505b9c823f676564c86a53745c6cf28026253


      # TODO need remove
      after_success:
      - npm run codecov
